version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      dependencies-major:
        patterns:
          - "*"
        update-types:
          - "major"
      dependencies-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/infra"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      dependencies-major:
        patterns:
          - "*"
        update-types:
          - "major"
      dependencies-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      dependencies-major:
        patterns:
          - "*"
        update-types:
          - "major"
      dependencies-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
